import { Route, Routes } from 'react-router-dom'
import { TADashboardPage } from '../pages/ta/TADashboardPage'
import { CandidatesPage, CandidateProfilePage } from '../pages/ta/CandidatesPage'
import { InterviewSetupPage } from '../pages/ta/InterviewSetupPage'
import { SlotRecommendationsPage } from '../pages/ta/SlotRecommendationsPage'
import { TAInterviewsPage } from '../pages/ta/TAInterviewsPage'
import { TACalendarPage } from '../pages/ta/TACalendarPage'
import { InterviewerDashboardPage } from '../pages/interviewer/InterviewerDashboardPage'
import { InterviewerInterviewsPage } from '../pages/interviewer/InterviewerInterviewsPage'
import { InterviewerDetailsPage } from '../pages/interviewer/InterviewerDetailsPage'
import { InterviewDetailsPage } from '../pages/interviews/InterviewDetailsPage'
import { InterviewerCalendarPage } from '../pages/interviewer/InterviewerCalendarPage'
import { LoginPage } from '../pages/common/LoginPage'
import { CandidateLoginPage } from '../pages/common/CandidateLoginPage'
import { InterviewerLoginPage } from '../pages/common/InterviewerLoginPage'
import { RoleSelectionPage } from '../pages/common/RoleSelectionPage'
import { NotificationsPage } from '../pages/notifications/NotificationsPage'
import { NotFoundPage } from '../pages/common/NotFoundPage'
import { AppShell } from '../components/layout/AppShell'
import { CandidateDashboardPage } from '../pages/candidate/CandidateDashboardPage'
import { CandidateInterviewsPage } from '../pages/candidate/CandidateInterviewsPage'
import { CandidateCalendarPage } from '../pages/candidate/CandidateCalendarPage'
import { CandidateNotificationsPage } from '../pages/candidate/CandidateNotificationsPage'

export function AppRoutes() { return <Routes><Route path="/" element={<RoleSelectionPage/>}/><Route path="/login" element={<RoleSelectionPage/>}/><Route path="/login/ta" element={<LoginPage/>}/><Route path="/login/candidate" element={<CandidateLoginPage/>}/><Route path="/login/interviewer" element={<InterviewerLoginPage/>}/><Route path="*" element={<AppShell><Routes><Route path="/candidate/dashboard" element={<CandidateDashboardPage/>}/><Route path="/candidate/interviews" element={<CandidateInterviewsPage/>}/><Route path="/candidate/calendar" element={<CandidateCalendarPage/>}/><Route path="/candidate/notifications" element={<CandidateNotificationsPage/>}/><Route path="/ta/dashboard" element={<TADashboardPage/>}/><Route path="/ta/candidates" element={<CandidatesPage/>}/><Route path="/ta/candidates/:candidateId" element={<CandidateProfilePage/>}/><Route path="/ta/candidates/:candidateId/setup-interview" element={<InterviewSetupPage/>}/><Route path="/ta/interviews" element={<TAInterviewsPage/>}/><Route path="/ta/interviews/create" element={<InterviewSetupPage create/>}/><Route path="/ta/interviews/:interviewId/slots" element={<SlotRecommendationsPage/>}/><Route path="/ta/calendar" element={<TACalendarPage/>}/><Route path="/interviewer/dashboard" element={<InterviewerDashboardPage/>}/><Route path="/interviewer/interviews" element={<InterviewerInterviewsPage/>}/><Route path="/interviewer/interviews/:interviewId" element={<InterviewerDetailsPage/>}/><Route path="/interviewer/calendar" element={<InterviewerCalendarPage/>}/><Route path="/interviews/:interviewId" element={<InterviewDetailsPage/>}/><Route path="/notifications" element={<NotificationsPage/>}/><Route path="*" element={<NotFoundPage/>}/></Routes></AppShell>}/></Routes> }
